functionsDirectory = "C:\\Users\\blarv\\Desktop\\MaintApp\\netlify\\functions"
functionsDirectoryOrigin = "config-v1"
plugins = []
headers = []
redirects = []

[build]
publish = "C:\\Users\\blarv\\Desktop\\MaintApp\\build"
publishOrigin = "config"
command = "npm run build"
commandOrigin = "config"
functions = "C:\\Users\\blarv\\Desktop\\MaintApp\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]